### ISSUE TITLE
EM27 sensor panel needs a minimum width for sensor values

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#122]
Tagging @dc2917.

Currently on my machine it looks like this:

![image](https://user-images.githubusercontent.com/23149834/225592636-139dc171-e904-4ca7-a077-b76c283f6b6f.png)

Ideally we want to be able to see the sensor values, whatever the size of the window. I'm not sure what the right fix is. Either we need to set a minimum width (in pixels) for the `QGridLayout`'s column or for the `QLineEdit`s themselves. Alternatively there may be an option to keep a `QLineEdit` wide enough that its text is always visible.

**Comment by dc2917** [comment]
Yeah, I had a go at sorting out the row sizes and scaling as I tried to line up the LED with the `QLineEdits` now that they're in separate layouts, but to no avail. Qt is quite annoying in this regard. I need to work out the right combination of setting `geometry`, `sizeHint`, `columnMinimumWidth`, `columnStretch`, as well as `setSizePolicy`.
