### ISSUE TITLE
Optionally append to existing data files

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#201]
Currently old data files will be overwritten, but it would be better if they could be
appended to.

@jonemurray Is this a feature you'd like?

**Comment by alexdewar** [comment]
It seems this isn't something the researchers actually want.

**Comment by jonemurray** [comment]
Over writing log data is not good and should be made impossible to do, that’s one reason for embedded time stamps in the filename

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexdewar** [comment]
Sounds good.

I've added a warning box if the user tries to overwrite data now. Re automatically adding timestamps to filenames: I think this is probably something we should talk about in person.

I'll close this issue.

**Comment by jonemurray** [comment]
Any time you want to drop by to talk let me know.

Cheers, Jon.
