### ISSUE TITLE
Remove unnecessary dependency on `pandas`

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#202]
This is caused by an upstream issue: https://github.com/ImperialCollegeLondon/pycsvy/issues/50

We can remove this once a new version of `pycsvy` is released.

Tagging @dalonsoa

**Comment by dalonsoa** [comment]
I'm not sure I understand the problem. `pycsvy` does not depend on `pandas`, right? If it is not there, that functionality simply is not available, but it is not a requirement.

**Comment by alexdewar** [comment]
Sorry, I should have given a bit more context.

Yes, that's how it should work, but if `pandas` isn't present then you get an error: https://github.com/ImperialCollegeLondon/pycsvy/issues/50

I've fixed it (https://github.com/ImperialCollegeLondon/pycsvy/pull/54) but we need the `pandas` dependency until we update to a newer version of `pycsvy` with this fix incorporated.

**Comment by dalonsoa** [comment]
Got it!
