### ISSUE TITLE
Power for TC4820s should be expressed as a percentage

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#289]
Currently it's displayed in the GUI as an integer between 0 and 511, which isn't v informative for the user.

**Comment by dc2917** [comment]
Is the the label next to the progress bar (power meter)? I don't actually think it's meant to show the power value at all, I think it's a string related to the alarm status. I had a dig through the C# code a while ago to try and work out what it was - I can't remember exactly, but I think it was something like the literal string of the hex value in the alarm message or something. It usually shows 40.

**Comment by alexdewar** [comment]
Yes it is.

That's a good idea. Thanks! I'll take a look at it.

**Comment by alexdewar** [comment]
This dropped off my radar, but it should hopefully be an easy fix and it's a good usability improvement.

Note that we already write the power level to the datafile as a proportion, so we could just change the API and have the `TC48020` class always return a proportion rather than the somewhat opaque integer values it currently emits.
