### ISSUE TITLE
Add support for interfacing with aircraft sensors over LAN

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#325]
After speaking to FAAM, it transpires that they have a RESTful API for accessing aircraft sensors in real time (their system is called DECADES). Apparently there is a new MQTT-based system in the works (DECADES-2), but it won't be operational until the end of 2025, so it won't be useful to us for now.

They stressed that this data should not be used for data analysis as it is of relatively low quality: the temporal resolution is only ~1s and there are no corrections applied. They say they can provide higher quality data (in netCDF format, IIRC) post flight. The lower quality data should still be good enough for our purposes: we just need to show it in the GUI as a guide to the user about what's going on.

It's debatable whether this data should be included in the CSV files at all, though if it is we should probably flag up that it's of low quality (maybe include "don't use" in the header name or something).

FAAM have a website for this, but there doesn't seem to be much useful documentation for us: https://www.faam.ac.uk/data-centre/live-data/

I've marked this as "Needs info" because we're still waiting to hear from FAAM about the details of their API. They also indicated that they should be able to provide us with an emulator (either on the web or as a Python script), which is probably necessary for us to be able to implement this feature.

**Comment by dc2917** [comment]
Email from FAAM (Subject: Re: Aircraft network protocol etc, Date: Fri, 05 Jan 2024 14:08:56) containing documentation on DECADES API, along with a link to download a docker environment for testing.

**Comment by dalonsoa** [comment]
@jonemurray , can you provide a list of sensors you want readings for?

**Comment by dc2917** [comment]
Thanks for your response @jonemurray 

We can query the DECADES database with `GET /decades/basic_data`, which returns the following:
- latitude
- longitude
- __pressure_height__ (~ altitude)
- __static_pressure__ (~ pressure)
- roll
- pitch
- heading
- __true_air_temp__ (~ outside air temperature)
- dew_point
- true_air_speed
- radar_height
- wind_speed
- wind_angle
- flight_number
- __utc_time__

This list seems like it contains the core parameter we'd want to make use of (bold indicates those you suggested above, as well as UTC time which we will also want).

We can also query the DECADES database with `GET /decades/params` which returns > 150 parameters, which I won't list here, but we can perhaps look through together soon to decide if you also want any of these.

**Comment by jamesturner246** [comment]
Hi @dc2917. Could you post a link to the doc/pdf here, please?

**Comment by jonemurray** [comment]
I've identified a serial to ethernet converter for UNIRAS, see link to the manual below. It's similar to the startech device FINESSE uses, but with the ethernet link. There is also a USB connector, which might be useful as the K107usb seneca device uses this. I'm not sure if the usb is configured for access this way.

I'd appreciate any thoughts you might have, before I purchase.

https://www.eztcp.com/en/download/pds_files/csch64en.pdf

**Comment by jamesturner246** [comment]
It looks like it would do the job, but some things worth noting:

1. It's *possible* that the USB ports are actually only used for programming the device and adding a WIFI dongle to it, not for adding your own USB devices. The manual is a bit unclear on this, so it's worth asking the manufacturer directly if you plan on using the USB port as part of the rig.
2. The programming software appears to be Windows only, and I've seen people have problems configuring on Linux. Maybe this isn't an issue for you, but something to consider if you have people on the team that don't use Windows.

**Comment by jonemurray** [comment]
Hi James,

Good points, as you’ll have seen I’ve passed these on to the supplier. Let’s see what comes back.

The usb port is a bonus, not absolutely required but very nice if we can make use of it.

Cheers, Jon.
