### ISSUE TITLE
Add panel for setting sequence of mirror positions

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#33]
Currently this is done via a bespoke scripting language (#16) and the GUI allows the user to choose a script file.

Depending on the design decisions we make, though, we may not want to use a script file at all but rather let the user choose the positions via a point-and-click interface.

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-122-23

**Comment by alexdewar** [comment]
@jonemurray Any thoughts about this?

I was wondering how complex the scripting language you designed is, e.g. does it have loops or anything in it? Or is it more like a static list of move instructions?

**Comment by alexdewar** [comment]
Thanks @jonemurray.

@dalonsoa Given Jon's response, I think maybe this one needs a bit more consideration and discussion with him, so perhaps we should hold off on it for now and do the other GUI-related tasks first.

The solutions to this as I see it are:

- Port the existing "scripting" language
- Replace it with a point-and-click interface (complicated by the fact that there are loops)
- Allow the user to control it with little Python scripts (which means we would have to expose the interface for moving the mirror somehow)

**Comment by dalonsoa** [comment]
I think the most sustainable solution will new to port the scripting language to a standard, and ideally human readable, format like YAML or TOML, so it is not an obscure combination of numbers and letters. 

Anyway, something to have a chat about, for sure.

**Comment by jonemurray** [comment]
Maybe we should have a brief discussion next week. Better still I can demonstrate the script if you want to pop over. Monday (not between 12-13) or Tuesday (not between 11:30 and 12:30, are good for me the rest of the week is full of meetings.

**Comment by alexdewar** [comment]
Thanks @jonemurray. @dalonsoa shall we have a chat about this today? (I thought I'd stick a note here so I don't forget to bring it up)

**Comment by jonemurray** [comment]
Hi Alex,

Yes let’s talk, I’m free other than between 12 and 1. So just suggest a time.

All the best, Jon.
