### ISSUE TITLE
Include user guide on GitHub Pages

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#346]
I think this task is optional. It *might* be worth doing if it's easy.

If we write the user guide in Markdown format, then hopefully we should be able to include it into the mkdocs-based workflow we're using to generate the developer documentation.

**Comment by dalonsoa** [comment]
If the user guide already written or it needs to be written? If it is the second, this is no small task!

**Comment by alexdewar** [comment]
There's a placeholder file there. @Sahil590 worked on the integration with the main program. So this is issue is just a case of publishing that file along with the other documentation.

Writing it is a separate issue: #350
