### ISSUE TITLE
Seneca K107 Checksum function

### ISSUE THREAD

**Issue by CWestICL** [ImperialCollegeLondon/FINESSE#400]
`senecak107.py` needs a checksum function written to check that data being read from the Seneca device hasn't been corrupted. The checksum formula hasn't been found in any of the device documentation so we may have to reverse-engineer the original C# code.

**Comment by dc2917** [comment]
Have you tried the method suggested [here](https://community.unix.com/t/modbus-rtu-rs485-packet-checksum-generation/387184/4) at all?

**Comment by CWestICL** [comment]
I haven't, good find! I'll see if I have any luck with this.

**Comment by dc2917** [comment]
```py
from crc import Calculator, Crc16
data = b"\x01\x03\x101d1p\xff\xfa\xff\xf81u\xff\xfa1d\xff\xfa]Z"

# checksum = data[-2:] = b"]Z" (ascii) = b"\0x5a\0x5d" (hex) = 23133 (dec)

calculator = Calculator(Crc16.MODBUS)
calculator.checksum(data[:-2])  # equals 23133
```

**Comment by CWestICL** [comment]
Amazing, been able to replicate this in the lab and it seems to be working! Turns out we were reversing the bytes when checking the supplied checksum from the end of the byte array when we didn't need to.
