### ISSUE TITLE
Window does not fit on screen

### ISSUE THREAD

**Issue by dc2917** [ImperialCollegeLondon/FINESSE#405]
The current layout and sizing of widgets prevents the entire window from fitting on my screen, and cannot be resized to make the window smaller due (presumably) to the size policies. Probably the matplotlib figure is responsible here.

The window cannot be maximised.

Also, minimizing the window and re-opening it causes a further change in sizing.

**Comment by alexdewar** [comment]
This *might* be fixed by #413. Would you mind giving it a whirl, @dc2917?

**Comment by dc2917** [comment]
Yeah, #413 makes the window fits nicely within the screen! Looks much better too.

**Comment by alexdewar** [comment]
Great. Thanks for checking :smile:
