### ISSUE TITLE
Make EM27 sensors code generic

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#457]
For the UNIRAS Project, we will be reading sensor values from the aircraft, instead of
the EM27. Given that the interfaces are likely to be similar, both the backend and
frontend code could be made more generic with little effort.

**Comment by dalonsoa** [comment]
This is about interfacing with the Decades software (see email sent in December).

**Comment by dalonsoa** [comment]
@jonemurray , are there any sensor readings to be taken from the spectrometer itself - not the aircraft - like voltages, temperatures of other things like that?

**Comment by dalonsoa** [comment]
It is unclear how to pull these from FTSW500, but they are displayed there. So, let's just use that software and not extracting them into FINESSE.

**Comment by alexdewar** [comment]
Reopening for further discussion. See #527
