### ISSUE TITLE
Synchronise timestamps between different sensors

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#488]
For UNIRAS, there are likely to be three kinds of data files produced which use different time sources:

1. The CSV files produced by the FINESSE program (using the laptop's system clock)
2. Spectrographic data from ABB's interferometer (using its own clock)
3. Aircraft sensor data, e.g. GPS coordinates etc. (using the aircraft's onboard clock, which is likely to be highly accurate)

Happily, FAAM report that they have an onboard NTP server, which should yield the same timestamps as used by the aircraft data, and ABB report that their interferometer can be configured to use an NTP server as a time source.

(Side note: I couldn't find an option for setting an NTP server in FTSW500 itself, so presumably it will have to be set on the actual interferometer. I've no idea how that will work. Someone will need to chase up ABB about this nearer the time.)

That leaves FINESSE. There are a couple of options here:

1. Configure Windows on the laptop to use the aircraft's NTP server to set the system clock
2. Use a Python library to retrieve the time correction from the NTP server directly (e.g. [ntplib](https://pypi.org/project/ntplib/))

I'm somewhat leaning towards 2 as the better option, because if we go with 1:

- FINESSE won't know whether or not Windows' time settings have been correctly configured
- FINESSE won't know whether synchronisation has happened yet or not
- We will need to provide careful instructions for researchers about how to configure Windows before they run FINESSE
- I'd worry that a Windows update might break something

If we decide to go with 2, we could perhaps have time sources as another kind of plugin. Then there'd be one for just using the system time (as would be used by the FINESSE rig) and one for NTP (as used by UNIRAS).

This will involve some refactoring and you might want to tackle #337 first.

Remember we are using UTC for timestamps!

Relevant xkcd: https://xkcd.com/2867

**Comment by jamesturner246** [comment]
> Relevant xkcd: https://xkcd.com/2867

Vicon would disagree... so long as you [pay for the privilege](Relevant xkcd: https://xkcd.com/2867)... -_-
