### ISSUE TITLE
logfile prompt

### ISSUE THREAD

**Issue by jonemurray** [ImperialCollegeLondon/FINESSE#526]
I was running some test yesterday and I realised that it is quite easy to not start the logfile running. The button is to the lower right and non-descript. This was also true with the original logfile button and setup. I missed starting this logging on a couple of occassions.

It would be worthwhile to have a pop up window appear, particularly when a script file is running to advise the user if their have not started logging.

**Comment by dc2917** [comment]
Potentially partially resolved by #517, as logfile button & setup are now in the significantly less cluttered left-hand side, but it could definitely be worth adding some form of indication for whether the logfile is being written to.
