### ISSUE TITLE
Display current mirror angle (esp. when running script)

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#583]
@jonemurray has requested that we indicate the current mirror angle somewhere on the
GUI. In particular, it seems that this feature would be useful when measure scripts are
running.

**Comment by alexdewar** [comment]
@jonemurray Would you still like to try to do this in the next engagement? It didn't make it into the proposal document but I can put it on our to-do list

**Comment by jonemurray** [comment]
Yes please

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexdewar** [comment]
Follow-up question: I've just realised it's not clear whether it would be sufficient to display the last known position of the mirror (i.e. when it was last stationary) or whether you'd like it to update more regularly (e.g. every second?).

To the team: even if @jonemurray wants the second of these, we still need to do the first one first, so this issue can still be started on.

**Comment by jonemurray** [comment]
Hi Alex,

That’s a good question, I think a more regular update would be useful. It’s useful to know it’s position and when the mirror is in motion, a 1 second update would allow this.

Cheers, Jon.

**Comment by alexdewar** [comment]
I've belatedly realised that you can't actually query the mirror's position while the motor is moving anyway, so we'll have to make do with just knowing its position when it's stationary (though we could also indicate when it is moving).

**Comment by jonemurray** [comment]
Knowing the mirror is moving is helpful.
