### ISSUE TITLE
Connecting to DECADES server now fails

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#665]
I'm not sure if the DECADES peeps have updated their docker images or what have you but I just tried running FINESSE with the DECADES sensors and it didn't work :disappointed:. I double-checked that it wasn't a recent breakage by going back to an old commit which should definitely work (7600211519266b8675f9af4ab013f00a02b4aaf4) and I was still getting the same error.

The problem is that the backend is requesting `/decades/params/availability` from the (simulated) DECADES server and getting a 404 back.

Do you have any ideas @jamesturner246?

**Comment by jamesturner246** [comment]
Huh. Seemed to work when I tried it. Nothing to do with zscaler, is it? Happy to have a chat and figure it out.

**Comment by alexdewar** [comment]
Oh, that's weird. So to be clear, you ran `docker compose up` and then opened the device in FINESSE? It could be a "me" issue

**Comment by jamesturner246** [comment]
I'm on finesse main, with the compose running, with Zscaler disabled. I'll send you the decades compose I'm using over teams.

Here's what I see in my nginx logs:

```
nginx         | 127.0.0.1 - - [25/Oct/2024:15:31:56 +0000] "GET /decades/params/availability HTTP/1.1" 200 24117 "-" "Mozilla/5.0"
nginx         | 127.0.0.1 - - [25/Oct/2024:15:31:56 +0000] "GET /decades/livedata&frm=1729870316&to=1729870316&para=static_pressure&para=deiced_true_air_temp_c&para=gin_altitude HTTP/1.1" 200 146 "-" "Mozilla/5.0"
```

**Comment by alexdewar** [comment]
The issue was indeed zscaler. D'oh!

Oh well. Working now.

**Comment by alexdewar** [comment]
Reopening because I'm having the same issue again and can't remember exactly how I fixed it :upside_down_face:. I've tried turning off zscaler from within the GUI and disabling the service files... Is there anything else I need to do?

**Comment by alexdewar** [comment]
Finally got this working with help from @cc-a. It seems like you actually have to *disable* the ZScaler services and reboot, rather than just stopping them.

**Comment by jamesturner246** [comment]
This Zscaler can be a real PITA, it seems.
