### ISSUE TITLE
Set up logging system

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE#9]
The program should log important messages to a log file somewhere.

The package we choose to do this will probably depend on other things, like which GUI
framework we are using.

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-122-1

**Comment by alexdewar** [comment]
@dalonsoa I've just been looking at this and wondering whether `PySide6` has built-in logging capabilities that we should be using or whether we should use Python's `logging` module. Do you have any experience with this?

**Comment by dalonsoa** [comment]
None that I know of. In the other Pyside project we had, we used the builtin login capabilities which, when customised, are pretty powerful.

**Comment by alexdewar** [comment]
Okey doke, just thought I'd check! In C++ if you use Qt you end up using it for
everything including logging etc. but I'd rather use Python's tbh.
